### ISSUE TITLE
Rotation around a point on the surface

### ISSUE THREAD

**Issue by ric-bianchi** [HSF/Qt3DExaminerViewer#2]
`Shift+left-click` lets users choose a point on the surface of a volume and set the rotation point to it. Rotation (Ctrl+click&drag) should then be performed around the selected point as the new rotation center. However, it seems that the center of rotation is not exactly the point selected by the user but a point nearby and not always on the surface of the given volume.

The rotation point should be set at exactly the point selected on the surface of the volume.

Could you check and fix this, @huajian1069 ? 
Thanks a lot!

Best, -- Riccardo.

**Comment by huajian1069** [comment]
This is solved since we correct the behavior of triangle Picking. Thanks to Ric.
