### ISSUE TITLE
When zooming out, a strange transparent sphere appears on the center, as a result the model behind the sphere is shaded

### ISSUE THREAD

**Issue by huajian1069** [HSF/Qt3DExaminerViewer#5]
The happens for all of the custom shapes that I built

**Comment by ric-bianchi** [comment]
Mmm...nothing comes to my mind right away, but I'll take a look as well.

**Comment by huajian1069** [comment]
This is corrected now. It turns out when the view center is beyond the far plane of camera lens, shapes will be shaded just like a transparent objects appears ahead of them.  So my solution is to specify a very large value for far plane, like this 
`m_camera->lens()->setPerspectiveProjection(45.0f, 16.0f/9.0f, 0.1f, 1000000.0f);`

**Comment by huajian1069** [comment]
fixed by dfd44accdf660465b7a7db204cf61baf04025698
