### ISSUE TITLE
When selecting an open volume from the geo browser, it gets closed

### ISSUE THREAD

**Issue by ric-bianchi** [HSF/Qt3DExaminerViewer#8]
If I open a volume, let's say one of the the `Passive` volumes in the `Step6` example file, I can see its `InnerPassive` child volume.

That reflects in the geo browser, where I can click on the `InnerPassive` label to jump to that volume.

But if I then click on the `Passive` label in the geo browser, the `Passive` is closed hiding the child volume and the `Passive` is shown in the view. 

Opened/Closed state should be preserved, because that is set by the user to inspect the geometry; so, clicking on the labels in the geo browser should only affect the camera position/movement, but not the opened/closed state of the volume.

----

P.S.

Or, we could add a switch to enable that on user's request; something like a lock: when "locked" then the opened/closed state is preserved while navigating through the geo browser; if "unlocked", then clicking on the labels in the geo browser opens/closes the related volumes in the view.
**That could be a new feature for one of the future releases.**

**Comment by ric-bianchi** [comment]
The view shows the Passive volume opened by the user, revealing the InnerPassive child volume. This is correctly reflected in the browser.

<img width="1312" alt="Screen Shot 2020-08-29 at 16 23 19" src="https://user-images.githubusercontent.com/17335100/91639149-ecb8c900-ea14-11ea-9405-10bc5c6f9357.png">

But clicking on the `Passive` label in the geo browser makes the `Passive` volume close:

<img width="1312" alt="Screen Shot 2020-08-29 at 16 23 27" src="https://user-images.githubusercontent.com/17335100/91639153-f17d7d00-ea14-11ea-8c30-63eaf331931f.png">

**Comment by huajian1069** [comment]
fixed by 068c404221c2ea64383619d9ade338ae220f227b
